default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  #username: <%= ENV['POSTGRES_USER'] %>
  #password: <%= ENV['POSTGRES_PASSWORD'] %>
  #host: <%= ENV['POSTGRES_HOST'] %>
  username: postgres
  password: 1
  host: localhost

development:
  <<: *default
  database: todo_dev
test:
  <<: *default
  database: todo_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
